# Generated by Django 4.2.2 on 2023-07-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('is_staff', models.BooleanField(default=False)),
                ('subscribed_categories', models.ManyToManyField(blank=True, related_name='subscribers', to='ads.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
