# Generated by Django 4.2.2 on 2023-07-13 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('category', models.CharField(choices=[('Tanks', 'Танки'), ('Healers', 'Хилы'), ('DD', 'ДД'), ('Merchants', 'Торговцы'), ('Guild Masters', 'Гилдмастеры'), ('Quest Givers', 'Квестгиверы'), ('Smiths', 'Кузнецы'), ('Tanner', 'Кожевники'), ('Potion', 'Зельевары'), ('Spellmasters', 'Мастера заклинаний')], default='Tanks', max_length=20, verbose_name='Category')),
                ('response_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(blank=True, help_text='загрузите файл', upload_to='uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advert', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(verbose_name='Response text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('status', models.BooleanField(default=False, verbose_name='Is accepted')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.advert')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ads.advert')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authored_response', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Category Name')),
                ('is_ad_category', models.BooleanField(default=False, verbose_name='Is Advertisement Category')),
                ('adverts', models.ManyToManyField(related_name='categories', to='ads.advert', verbose_name='Adverts')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
