# Generated by Django 4.2.2 on 2023-07-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'permissions': [('response_create', 'Can create response')], 'verbose_name': 'Отклик', 'verbose_name_plural': 'Отклики'},
        ),
    ]
