# Generated by Django 4.2.2 on 2023-07-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_response_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='article',
        ),
    ]
